### PR TITLE
Add ressource checks

### PR DESCRIPTION
**Pull request by Jibec**
When packaging an application, the package_checker can tell installation is successful, while important resources are missing, like JavaScript or CSS files.

If those files are missing, it probably means there is a path issue and the installation isn't full successful.
Note this patch was tested for locale resources, I don't know how it behaves with external resources (mostly CDN).

It surely needs more testing!

Double slash URL is not replaced, as it can exist on purpose... It is named "Protocol-relative URLs" https://en.wikipedia.org/wiki/URL#prurl

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
It could be interresting to have a look at wget.

With `wget --adjust-extension --page-requisites http://site.tld` for exemple.

**Comment by maniackcrudelis** [comment]
Just for information, something interesting with
`LC_ALL=C wget --adjust-extension --page-requisites --no-check-certificate http://site.tld 2>&1 | grep "^--.*--  https://\|HTTP request sent"`

**Comment by Jibec** [comment]
I don't understand why you want to use wget so much, what's the problem with curl?
Your command can't tell what link was requested, which isn't really useful for the packager to understand :p

**Comment by maniackcrudelis** [comment]
Because instead of all your code, with one line
`LC_ALL=C wget --adjust-extension --page-requisites --no-check-certificate https://crudelis-test5.fr/leed 2>&1 | grep "^--.*--  https://\|HTTP request sent"`
I obtain
```
--2017-11-13 20:28:33--  https://crudelis-test5.fr/leed
HTTP request sent, awaiting response... 301 Moved Permanently
--2017-11-13 20:28:33--  https://crudelis-test5.fr/leed/
HTTP request sent, awaiting response... 200 OK
--2017-11-13 20:28:33--  https://crudelis-test5.fr/robots.txt
HTTP request sent, awaiting response... 302 Moved Temporarily
--2017-11-13 20:28:33--  https://crudelis-test5.fr/yunohost/sso/?r=aHR0cHM6Ly9jcnVkZWxpcy10ZXN0NS5mci9yb2JvdHMudHh0
HTTP request sent, awaiting response... 200 OK
--2017-11-13 20:28:33--  https://crudelis-test5.fr/leed/templates/marigolds/css/style.css
HTTP request sent, awaiting response... 502 Bad Gateway
--2017-11-13 20:28:33--  https://crudelis-test5.fr/ynhpanel.js
HTTP request sent, awaiting response... 302 Moved Temporarily
--2017-11-13 20:28:33--  https://crudelis-test5.fr/yunohost/sso/?r=aHR0cHM6Ly9jcnVkZWxpcy10ZXN0NS5mci95bmhwYW5lbC5qcw==
HTTP request sent, awaiting response... 200 OK
--2017-11-13 20:28:33--  https://crudelis-test5.fr/leed/templates/marigolds/js/libs/jqueryAndModernizr.min.js
HTTP request sent, awaiting response... 502 Bad Gateway
--2017-11-13 20:28:33--  https://crudelis-test5.fr/leed/templates/marigolds/js/script.js
HTTP request sent, awaiting response... 502 Bad Gateway
```
Which seems easier to analyse ;)

> But here, I've modified the nginx conf to force a 502 for /leed/templates

**Comment by Jibec** [comment]
Well, Fedora doesn't have the same output, that's probably the reason why I didn't understood the proposal...

[jb@fixe ~]$  LC_ALL=C wget --adjust-extension --page-requisites --no-check-certificate https://holcroft.fr/weblate 2>&1 | grep "^--.*-- https://\|HTTP request sent"
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 302 Moved Temporarily
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 302 Moved Temporarily
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 200 OK
HTTP request sent, awaiting response... 404 Not Found

**Comment by maniackcrudelis** [comment]
Here https://github.com/YunoHost/package_check/pull/38 my proposal for a check of the resources with wget.

**Pull request closed without merging**
