### PR TITLE
Extract base tag href for resolving asset URLs

### PR DESCRIPTION
**Pull request by fflorent**
## Context

My [Grist package](https://github.com/YunoHost-Apps/grist_ynh) is marked as broken since package_check has checked the assets.

By taking a closer look, I realized that it wasn't an issue of my package, nor of the upstream app, but of the checker.

Indeed, the browser resolves assets (scripts and stylesheets) paths either from the domain, but also if present using the `<base>` tag ([mdn documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base)).

## Proposed solution

1. We extract the base domain
2. We use [urljoin](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin) to resolve the asset full url (base can be of the form `https://{domain}/path/to/` or a absolute path without the domain like `/path/to/`).

### CODE REVIEW

**Comment by alexAubin** [comment]
LGTM, cheers also for the urljoin trick :+1:

**Comment by alexAubin** [comment]
@fflorent : note that I just reverted this PR as it's been breaking the CI for a few days now, in particular because now the tests on "install on subpath" scenario tries to access the app on `domain.tld` instead of `domain.tld/path`

This seems related to this unexpected behavior of `urljoin` : 

```python
>>> urljoin("https://foo.tld/path", "/")
'https://foo.tld/'
>>> urljoin("https://foo.tld/path", "")
'https://foo.tld/path'
```

**Comment by fflorent** [comment]
@alexAubin Do you have an example of an app which fails, so I can reproduce locally? (if possible, one for which it is quick to run the CI).

**Comment by alexAubin** [comment]
For example https://github.com/YunoHost-Apps/243-game_ynh

**Pull request merged**
