### PR TITLE
add network monitoring

### PR DESCRIPTION
**Pull request by Jibec**

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
A little bit of explanation maybe...

**Comment by Jibec** [comment]
We consumes too much bandwith for our tests. Behind the waste of resources (which is enormous over time), it also takes a significant time to download. Especially with low bandwidth (ADSL, network, etc.).

I'd like to help setting up a local caching in the future.
The first step is to measure what we consume, so we can monitor progress.

**Comment by maniackcrudelis** [comment]
Do you have a slightest idea of how it would be difficult to cache all is needed by the system, how are you going to give to each part what it needs, apt, pip, node, git, etc !?

I don't think that it would really worth all this work...
Anyway, we can merge that in a new branch to keep that aside if you want to work on this matter.

**Comment by Jibec** [comment]
Yes, it will take time, but step by step it should be doable

**Pull request closed without merging**
