### PR TITLE
say Y by default if lock is present

### PR DESCRIPTION
**Pull request by Jibec**

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
That's the idea, it's not Yes by default.
By default, you should not run package check if there's a lock.

**Comment by Jibec** [comment]
Le 17 décembre 2017 15:58:51 GMT+01:00, Maniack Crudelis <notifications@github.com> a écrit :
>That's the idea, it's not Yes by default.
>By default, you should not run package check if there's a lock.

The most current usecase I have is I cancel it on purpose because one step of the install fails.
The full test suite or weblate is 55 min, I cancel package check quite often.
-- 
Jean-Baptiste Holcroft

**Comment by maniackcrudelis** [comment]
Yes so do I.
But, when you do that, you have to do it on purpose. So you have to say clearly you agree to rerun package check.

**Comment by Jibec** [comment]
What are the potential issues you foresee?
-- 
Jean-Baptiste Holcroft

**Comment by maniackcrudelis** [comment]
Running package check while another instance is already running.
That's why there's a lock.

**Comment by Jibec** [comment]
So, it will crash the other instance, without impacting the new launch, isn't it?
-- 
Jean-Baptiste Holcroft

**Comment by maniackcrudelis** [comment]
Trying to running 2 times the same lxc container at the same time will have a unmanaged behavior.
And there're also a lot of other sub-process which not suppose to have a conflict behavior.

So, there's a lock to avoid this cases.

**Comment by Jibec** [comment]
Well, I understand we won't reach a solution, you may close this PR. No hard feelings.
-- 
Jean-Baptiste Holcroft

**Pull request closed without merging**
